# Vectorization

In [1]:
import time
import numpy as np

In [2]:
N = 10000000

a = np.random.rand(N)
b = np.random.rand(N)

### For Loop


In [3]:
c = 0
tic = time.time()

for i in range(N):
    c += a[i] * b[i]
    
toc = time.time()

print(c)
print(f"For Loop: {1000 * (toc - tic)}ms")

2499288.0695771333
For Loop: 1619.4641590118408ms


### Vectorized


In [4]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print(f"Vectorized: {1000 * (toc - tic)}ms")

2499288.069577044
Vectorized: 5.753993988037109ms


---

# Broadcasting


In [5]:
A = np.array(
    [
        [56.0, 0.0, 4.4, 68.0],
        [1.2, 104.0, 52.0, 8.0],
        [1.8, 135.0, 99.0, 0.9]
    ]
)

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100 * A / cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


---

# Python-Numpy Vectors


Use this:

In [8]:
a = np.random.randn(5, 1)
print(a)
print(a.shape)

[[ 0.08220598]
 [-1.22676113]
 [ 0.74933398]
 [ 0.0784126 ]
 [ 1.47392726]]
(5, 1)


Not this:


In [9]:
a = np.random.randn(5)
print(a)
print(a.shape)

[-0.23137974  1.40446102  0.01229801 -0.1246042  -1.72291778]
(5,)


Use assert also!

In [10]:
assert (a.shape == (5,)) # should be (5, 1)!